import { createConstants } from 'utils/';

export default createConstants(
  'SOUNDS_ADD_LOCAL',
  'SOUNDS_REQUEST',
  'SOUNDS_MUTE',
  'SOUNDS_PLAY',
  'SOUNDS_RECEIVED',
  'SOUNDS_VOLUME',
  'SOUNDS_EDIT',
  'SOUNDS_REMOVE',
  'SOUNDS_ADD_CUSTOM',
  'SOUNDS_ADD_YOUTUBE',
  'SOUNDS_ADD_SOUNDCLOUD',
  'SOUNDS_DOWNLOADING',
  'SOUNDS_DOWNLOADED',
  'SOUNDS_ERROR',
  'SOUNDS_RESET'
);
